package main

import (
	"flag"
	"log"
	"net/http"

	"github.com/elazarl/goproxy"
)

func main() {
	verbose := flag.Bool("v", false, "should every proxy request be logged to stdout")
	addr := flag.String("addr", ":8080", "proxy listen address")
	flag.Parse()
	proxy := goproxy.NewProxyHttpServer()
	proxy.Verbose = *verbose
	log.Fatal(http.ListenAndServe(*addr, proxy))
}

type AutoGenerated struct {
	CurrentServiceTime string `json:"CurrentServiceTime"`
	ResultType         int    `json:"ResultType"`
	Obj                struct {
		CurrencySelections  []interface{} `json:"CurrencySelections"`
		DefaultCurrency     string        `json:"DefaultCurrency"`
		IsNewAddOrder       bool          `json:"IsNewAddOrder"`
		IsShowBigPic        bool          `json:"IsShowBigPic"`
		MemberRightSubTitle string        `json:"MemberRightSubTitle"`
		MemberRightTitle    string        `json:"MemberRightTitle"`
		MemberRightVisible  bool          `json:"MemberRightVisible"`
		MemberRights        []struct {
			RightsGradeIconURL string `json:"RightsGradeIconUrl"`
			RightsGradeName    string `json:"RightsGradeName"`
			Rank               int    `json:"rank"`
		} `json:"MemberRights"`
		NewChannels string `json:"NewChannels"`
		Rooms       []struct {
			Activities []struct {
				BelowPriceText  string `json:"BelowPriceText"`
				BookingFormText struct {
					Color string `json:"Color"`
					Icon  string `json:"Icon"`
					Text  string `json:"Text"`
				} `json:"BookingFormText"`
				ID              string   `json:"Id"`
				IsAgreement     bool     `json:"IsAgreement"`
				IsHornorgift    bool     `json:"IsHornorgift"`
				IsNeedOnlinePay bool     `json:"IsNeedOnlinePay"`
				IsPresent       bool     `json:"IsPresent"`
				IsQuestionMark  bool     `json:"IsQuestionMark"`
				Name            string   `json:"Name"`
				PrePayType      int      `json:"PrePayType"`
				PriceTags       []string `json:"PriceTags"`
				Prices          []struct {
					Currency    string `json:"Currency"`
					MarketPrice int    `json:"MarketPrice"`
					Price       int    `json:"Price"`
					Saved       int    `json:"Saved"`
					TaxAmount   int    `json:"TaxAmount"`
				} `json:"Prices"`
				QuestionMarkDetails  []string `json:"QuestionMarkDetails,omitempty"`
				QuestionMarkTitle    string   `json:"QuestionMarkTitle,omitempty"`
				Rank                 int      `json:"Rank"`
				ResvType             string   `json:"ResvType"`
				Stock                int      `json:"Stock"`
				TargetChannel        string   `json:"TargetChannel"`
				CancellationTimeText struct {
					ImgURL string `json:"imgUrl"`
					Text   string `json:"text"`
					Text2  string `json:"text2"`
				} `json:"cancellationTimeText"`
				IsFixedPrice   bool `json:"isFixedPrice"`
				IsLastRoom     bool `json:"isLastRoom"`
				IsMemberPrice  bool `json:"isMemberPrice"`
				IsMinimumPrice bool `json:"isMinimumPrice"`
				IsNightSnack   bool `json:"isNightSnack"`
				IsRoomDiscount bool `json:"isRoomDiscount"`
				PointExchange  bool `json:"pointExchange"`
				PriceRightTags []struct {
					TagText string `json:"tagText"`
					Type    int    `json:"type"`
				} `json:"priceRightTags"`
				XpmsActivityID string `json:"xpmsActivityId"`
			} `json:"Activities"`
			AddBed            string `json:"AddBed"`
			Area              string `json:"Area"`
			Bed               string `json:"Bed"`
			BedSize           string `json:"BedSize"`
			Floor             string `json:"Floor"`
			HasLived          bool   `json:"HasLived"`
			ID                string `json:"Id"`
			IsShowDetail      bool   `json:"IsShowDetail"`
			IsStockLittle     bool   `json:"IsStockLittle"`
			LowestMarketPrice int    `json:"LowestMarketPrice"`
			LowestPrice       int    `json:"LowestPrice"`
			LowestPriceList   []struct {
				Currency    string `json:"Currency"`
				MarketPrice int    `json:"MarketPrice"`
				Price       int    `json:"Price"`
				Saved       int    `json:"Saved"`
				TaxAmount   int    `json:"TaxAmount"`
			} `json:"LowestPriceList"`
			MaxCheckInNum  int      `json:"MaxCheckInNum"`
			Name           string   `json:"Name"`
			People         string   `json:"People"`
			Photo          string   `json:"Photo"`
			Photos         []string `json:"Photos"`
			Rank           int      `json:"Rank"`
			Remark         string   `json:"Remark"`
			ResvType       string   `json:"ResvType"`
			ShowCount      int      `json:"ShowCount"`
			Smoke          string   `json:"Smoke"`
			StockType      string   `json:"StockType"`
			ValidCurrencys []struct {
				CurrencyCode string `json:"CurrencyCode"`
				CurrencyName string `json:"CurrencyName"`
			} `json:"ValidCurrencys"`
			Wifi                         string        `json:"Wifi"`
			Window                       string        `json:"Window"`
			HasCanReservePointExchange   bool          `json:"hasCanReservePointExchange"`
			HourRoomCheckInTime          string        `json:"hourRoomCheckInTime"`
			RoomLowestPointExchangePoint int           `json:"roomLowestPointExchangePoint"`
			SupportRoomDiscount          bool          `json:"supportRoomDiscount"`
			Tags                         []interface{} `json:"tags"`
		} `json:"Rooms"`
		ShowCount      int    `json:"ShowCount"`
		ExtraInfos     string `json:"extraInfos"`
		HasReserveRoom bool   `json:"hasReserveRoom"`
		MaxCheckInNum  int    `json:"maxCheckInNum"`
	} `json:"obj"`
}
